name: Publish
on:
  release:
    types: [ published ]

jobs:
  formula:
    runs-on: macos-latest
    steps:
    - name: Update Homebrew Formula
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        formula: td
        livecheck: true
